### ISSUE TITLE
blog status

### ISSUE THREAD

**Issue by timokau** [regnat/ptyx#7]
This might not be quite the right place to ask about it, but its the best I found.

https://typing-nix.regnat.ovh/ gives a 502 right now. Is the blog discontinued, or is that just a temporary error?

**Comment by regnat** [comment]
That's definitely not normal (although there hasn't been any activity on it for a long time), I'll look into it. Thanks for reporting

**Comment by regnat** [comment]
It should be accessible again now, feel free to reopen if it isn't case

**Comment by timokau** [comment]
Thanks! I just noticed my rss reader complaining about a dead link.
